# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='prize',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Beer'), (2, 'Merchandise')], default=0),
        ),
    ]
